### ISSUE TITLE
make it available as a desktop app or an extension

### ISSUE THREAD

**Issue by Mazuh** [Mazuh/octo-tasks#7]
if it's easy enough to do so

**Comment by gustavoFreireS** [comment]
what kind of packages are needed? (.deb, .dmg, .exe, .msi) I could provide any of the listed ones.

**Comment by gustavoFreireS** [comment]
the app needed to be always on top of windows or could it be on background?

**Comment by Mazuh** [comment]
resolved by https://github.com/Mazuh/octo-tasks/commit/0231b56d9ba3a5ed07d485b5dc36d65689fd4ce8 and https://github.com/Mazuh/octo-tasks/commit/cb0f1d5cbdc18d7a384dcfc439df223d954dc01e
